-- =====================================================================
-- ADOPET — V1: estructura inicial de la base de datos
-- Politécnico Colombiano Jaime Isaza Cadavid
-- Juan Sebastián Pérez Morales / Valeria Piedrahita Arbeláez
-- Motor: Oracle XE 21c
--
-- Migración de Flyway. 27 tablas. Solo estructura: no inserta datos.
-- Se aplica con:  flyway "-configFiles=db/flyway.conf" migrate
-- NO se edita una vez aplicada: cualquier cambio va en una migración nueva.
--
-- Orden del script:
--   1. Tablas de catálogo
--   2. Tablas de acceso y menú
--   3. Tablas de mascotas
--   4. Tablas de adopción y seguimiento
--   5. Llaves foráneas
--   6. Índices únicos condicionales y funcionales
-- =====================================================================


-- =====================================================================
-- 1. CATÁLOGOS
-- Los de estado y etapa llevan ID fijo, sin IDENTITY, porque los
-- índices únicos condicionales los referencian por valor.
-- =====================================================================

CREATE TABLE ESTADOS_MASCOTA (
  ID_ESTADO_MASCOTA  NUMBER        NOT NULL,
  NOMBRE             VARCHAR2(20)  NOT NULL,
  ES_VISIBLE         CHAR(1)       NOT NULL,
  ES_ADOPTABLE       CHAR(1)       NOT NULL,
  ACTIVO             CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_ESTADOS_MASCOTA    PRIMARY KEY (ID_ESTADO_MASCOTA),
  CONSTRAINT UQ_ESTADOS_MASCOTA    UNIQUE (NOMBRE),
  CONSTRAINT CK_ESTMAS_VISIBLE     CHECK (ES_VISIBLE   IN ('S','N')),
  CONSTRAINT CK_ESTMAS_ADOPTABLE   CHECK (ES_ADOPTABLE IN ('S','N')),
  CONSTRAINT CK_ESTMAS_ACTIVO      CHECK (ACTIVO       IN ('S','N'))
);

CREATE TABLE ESTADOS_PROCESO (
  ID_ESTADO_PROCESO  NUMBER        NOT NULL,
  NOMBRE             VARCHAR2(20)  NOT NULL,
  ACTIVO             CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_ESTADOS_PROCESO    PRIMARY KEY (ID_ESTADO_PROCESO),
  CONSTRAINT UQ_ESTADOS_PROCESO    UNIQUE (NOMBRE),
  CONSTRAINT CK_ESTPRO_ACTIVO      CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE ETAPAS_SEGUIMIENTO (
  ID_ETAPA            NUMBER        NOT NULL,
  NOMBRE              VARCHAR2(10)  NOT NULL,
  DIAS_DESDE_ENTREGA  NUMBER        NOT NULL,
  ACTIVO              CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_ETAPAS_SEGUIMIENTO PRIMARY KEY (ID_ETAPA),
  CONSTRAINT UQ_ETAPAS_NOMBRE      UNIQUE (NOMBRE),
  CONSTRAINT UQ_ETAPAS_DIAS        UNIQUE (DIAS_DESDE_ENTREGA),
  CONSTRAINT CK_ETAPAS_DIAS        CHECK (DIAS_DESDE_ENTREGA > 0),
  CONSTRAINT CK_ETAPAS_ACTIVO      CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE SEMAFOROS (
  ID_SEMAFORO   NUMBER        NOT NULL,
  NOMBRE        VARCHAR2(10)  NOT NULL,
  PUNTAJE_MIN   NUMBER(3,2)   NOT NULL,
  PUNTAJE_MAX   NUMBER(3,2)   NOT NULL,
  ACTIVO        CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_SEMAFOROS       PRIMARY KEY (ID_SEMAFORO),
  CONSTRAINT UQ_SEMAFOROS       UNIQUE (NOMBRE),
  CONSTRAINT CK_SEMAFORO_RANGO  CHECK (PUNTAJE_MAX >= PUNTAJE_MIN),
  CONSTRAINT CK_SEMAFORO_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE PREGUNTAS_CHECKPOINT (
  ID_PREGUNTA  NUMBER GENERATED AS IDENTITY,
  TEXTO        VARCHAR2(200)  NOT NULL,
  ORDEN        NUMBER         NOT NULL,
  ACTIVO       CHAR(1)        DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_PREGUNTAS_CHECKPOINT PRIMARY KEY (ID_PREGUNTA),
  CONSTRAINT CK_PREGUNTAS_ACTIVO     CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE OPCIONES_CHECKPOINT (
  ID_OPCION    NUMBER GENERATED AS IDENTITY,
  ID_PREGUNTA  NUMBER         NOT NULL,
  TEXTO        VARCHAR2(200)  NOT NULL,
  PUNTAJE      NUMBER(1)      NOT NULL,
  ES_ALARMA    CHAR(1)        DEFAULT 'N' NOT NULL,
  ORDEN        NUMBER         NOT NULL,
  ACTIVO       CHAR(1)        DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_OPCIONES_CHECKPOINT PRIMARY KEY (ID_OPCION),
  CONSTRAINT UQ_OPCION_PREGUNTA     UNIQUE (ID_OPCION, ID_PREGUNTA),
  CONSTRAINT CK_OPCHK_PUNTAJE       CHECK (PUNTAJE > 0),
  CONSTRAINT CK_OPCHK_ALARMA        CHECK (ES_ALARMA IN ('S','N')),
  CONSTRAINT CK_OPCHK_ACTIVO        CHECK (ACTIVO    IN ('S','N'))
);

CREATE TABLE TIPOS_NOTIFICACION (
  ID_TIPO_NOTIFICACION  NUMBER        NOT NULL,
  NOMBRE                VARCHAR2(30)  NOT NULL,
  ES_PARA_STAFF         CHAR(1)       NOT NULL,
  PRIORIDAD             NUMBER(1)     NOT NULL,
  ACTIVO                CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_TIPOS_NOTIFICACION PRIMARY KEY (ID_TIPO_NOTIFICACION),
  CONSTRAINT UQ_TIPOS_NOTIFICACION UNIQUE (NOMBRE),
  CONSTRAINT CK_TIPNOT_STAFF       CHECK (ES_PARA_STAFF IN ('S','N')),
  CONSTRAINT CK_TIPNOT_ACTIVO      CHECK (ACTIVO        IN ('S','N'))
);

CREATE TABLE ESPECIES (
  ID_ESPECIE  NUMBER        NOT NULL,
  NOMBRE      VARCHAR2(10)  NOT NULL,
  ACTIVO      CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_ESPECIES      PRIMARY KEY (ID_ESPECIE),
  CONSTRAINT UQ_ESPECIES      UNIQUE (NOMBRE),
  CONSTRAINT CK_ESPECIE_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE RAZAS (
  ID_RAZA     NUMBER GENERATED AS IDENTITY,
  ID_ESPECIE  NUMBER        NOT NULL,
  NOMBRE      VARCHAR2(50)  NOT NULL,
  ACTIVO      CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_RAZAS           PRIMARY KEY (ID_RAZA),
  CONSTRAINT UQ_RAZA_POR_ESPECIE UNIQUE (ID_ESPECIE, NOMBRE),
  CONSTRAINT CK_RAZA_ACTIVO      CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE TAMANIOS (
  ID_TAMANIO  NUMBER        NOT NULL,
  NOMBRE      VARCHAR2(10)  NOT NULL,
  ACTIVO      CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_TAMANIOS      PRIMARY KEY (ID_TAMANIO),
  CONSTRAINT UQ_TAMANIOS      UNIQUE (NOMBRE),
  CONSTRAINT CK_TAMANIO_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE SEXOS (
  ID_SEXO  NUMBER        NOT NULL,
  NOMBRE   VARCHAR2(10)  NOT NULL,
  ACTIVO   CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_SEXOS      PRIMARY KEY (ID_SEXO),
  CONSTRAINT UQ_SEXOS      UNIQUE (NOMBRE),
  CONSTRAINT CK_SEXO_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE NIVELES_ENERGIA (
  ID_NIVEL_ENERGIA  NUMBER        NOT NULL,
  NOMBRE            VARCHAR2(10)  NOT NULL,
  ACTIVO            CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_NIVELES_ENERGIA PRIMARY KEY (ID_NIVEL_ENERGIA),
  CONSTRAINT UQ_NIVELES_ENERGIA UNIQUE (NOMBRE),
  CONSTRAINT CK_NIVENE_ACTIVO   CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE TIPOS_DOCUMENTO (
  ID_TIPO_DOCUMENTO  NUMBER        NOT NULL,
  NOMBRE             VARCHAR2(15)  NOT NULL,
  ACTIVO             CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_TIPOS_DOCUMENTO PRIMARY KEY (ID_TIPO_DOCUMENTO),
  CONSTRAINT UQ_TIPOS_DOCUMENTO UNIQUE (NOMBRE),
  CONSTRAINT CK_TIPDOC_ACTIVO   CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE CIUDADES (
  ID_CIUDAD  NUMBER GENERATED AS IDENTITY,
  NOMBRE     VARCHAR2(80)  NOT NULL,
  ACTIVO     CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_CIUDADES      PRIMARY KEY (ID_CIUDAD),
  CONSTRAINT UQ_CIUDADES      UNIQUE (NOMBRE),
  CONSTRAINT CK_CIUDAD_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE TIPOS_VIVIENDA (
  ID_TIPO_VIVIENDA  NUMBER        NOT NULL,
  NOMBRE            VARCHAR2(15)  NOT NULL,
  ACTIVO            CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_TIPOS_VIVIENDA PRIMARY KEY (ID_TIPO_VIVIENDA),
  CONSTRAINT UQ_TIPOS_VIVIENDA UNIQUE (NOMBRE),
  CONSTRAINT CK_TIPVIV_ACTIVO  CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE TIEMPOS_DISPONIBLES (
  ID_TIEMPO_DISPONIBLE  NUMBER        NOT NULL,
  NOMBRE                VARCHAR2(10)  NOT NULL,
  ACTIVO                CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_TIEMPOS_DISPONIBLES PRIMARY KEY (ID_TIEMPO_DISPONIBLE),
  CONSTRAINT UQ_TIEMPOS_DISPONIBLES UNIQUE (NOMBRE),
  CONSTRAINT CK_TIEDIS_ACTIVO       CHECK (ACTIVO IN ('S','N'))
);


-- =====================================================================
-- 2. ACCESO Y MENÚ
-- =====================================================================

CREATE TABLE ROLES (
  ID_ROL      NUMBER GENERATED AS IDENTITY,
  NOMBRE_ROL  VARCHAR2(30)  NOT NULL,
  CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL),
  CONSTRAINT UQ_ROLES UNIQUE (NOMBRE_ROL)
);

CREATE TABLE PERFILES (
  ID_PERFIL      NUMBER GENERATED AS IDENTITY,
  ID_ROL         NUMBER        NOT NULL,
  NOMBRE_PERFIL  VARCHAR2(50)  NOT NULL,
  ACTIVO         CHAR(1)       DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_PERFILES      PRIMARY KEY (ID_PERFIL),
  CONSTRAINT CK_PERFIL_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE OPCIONES_MENU (
  ID_OPCION_MENU  NUMBER GENERATED AS IDENTITY,
  NOMBRE_OPCION   VARCHAR2(50)   NOT NULL,
  ETIQUETA        VARCHAR2(50)   NOT NULL,
  RUTA            VARCHAR2(100)  NOT NULL,
  ORDEN           NUMBER         NOT NULL,
  ACTIVO          CHAR(1)        DEFAULT 'S' NOT NULL,
  CONSTRAINT PK_OPCIONES_MENU PRIMARY KEY (ID_OPCION_MENU),
  CONSTRAINT UQ_OPCIONES_MENU UNIQUE (NOMBRE_OPCION),
  CONSTRAINT CK_OPCMEN_ACTIVO CHECK (ACTIVO IN ('S','N'))
);

CREATE TABLE PERFILES_OPCIONES (
  ID_PERFIL       NUMBER   NOT NULL,
  ID_OPCION_MENU  NUMBER   NOT NULL,
  CREAR           CHAR(1)  DEFAULT 'N' NOT NULL,
  MODIFICAR       CHAR(1)  DEFAULT 'N' NOT NULL,
  ELIMINAR        CHAR(1)  DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_PERFILES_OPCIONES PRIMARY KEY (ID_PERFIL, ID_OPCION_MENU),
  CONSTRAINT CK_PEROPC_CREAR      CHECK (CREAR     IN ('S','N')),
  CONSTRAINT CK_PEROPC_MODIFICAR  CHECK (MODIFICAR IN ('S','N')),
  CONSTRAINT CK_PEROPC_ELIMINAR   CHECK (ELIMINAR  IN ('S','N'))
);

CREATE TABLE USUARIOS (
  DOCUMENTO          VARCHAR2(20)   NOT NULL,
  ID_PERFIL          NUMBER         NOT NULL,
  NOMBRE             VARCHAR2(100)  NOT NULL,
  CORREO             VARCHAR2(150)  NOT NULL,
  CONTRASENA_HASH    VARCHAR2(255)  NOT NULL,
  ID_TIPO_DOCUMENTO  NUMBER         NOT NULL,
  TELEFONO           VARCHAR2(20)   NOT NULL,
  DIRECCION          VARCHAR2(200)  NOT NULL,
  ID_CIUDAD          NUMBER         NOT NULL,
  FECHA_NACIMIENTO   DATE           NOT NULL,
  ACTIVO             CHAR(1)        DEFAULT 'S' NOT NULL,
  FECHA_REGISTRO     DATE           DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_USUARIOS       PRIMARY KEY (DOCUMENTO),
  CONSTRAINT CK_USUARIO_ACTIVO CHECK (ACTIVO IN ('S','N'))
);


-- =====================================================================
-- 3. MASCOTAS
-- =====================================================================

CREATE TABLE MASCOTAS (
  ID_MASCOTA                    NUMBER GENERATED AS IDENTITY,
  NOMBRE                        VARCHAR2(50)   NOT NULL,
  ID_RAZA                       NUMBER         NOT NULL,
  EDAD_MESES_INGRESO            NUMBER(3)      NOT NULL,
  ID_TAMANIO                    NUMBER         NOT NULL,
  ID_SEXO                       NUMBER         NOT NULL,
  ID_NIVEL_ENERGIA              NUMBER         NOT NULL,
  COMPATIBLE_NINOS              CHAR(1)        NOT NULL,
  COMPATIBLE_OTRAS_MASCOTAS     CHAR(1)        NOT NULL,
  TIENE_NECESIDADES_ESPECIALES  CHAR(1)        NOT NULL,
  DESCRIPCION_NECESIDADES       VARCHAR2(500),
  FECHA_INGRESO                 DATE           DEFAULT SYSDATE NOT NULL,
  FECHA_SALIDA                  DATE,
  ID_ESTADO_MASCOTA             NUMBER         DEFAULT 1 NOT NULL,
  ACTIVO                        CHAR(1)        DEFAULT 'S' NOT NULL,
  OBSERVACIONES_ESTADO          VARCHAR2(200),
  CONSTRAINT PK_MASCOTAS          PRIMARY KEY (ID_MASCOTA),
  CONSTRAINT CK_MASCOTA_EDAD      CHECK (EDAD_MESES_INGRESO > 0),
  CONSTRAINT CK_MASCOTA_NINOS     CHECK (COMPATIBLE_NINOS          IN ('S','N')),
  CONSTRAINT CK_MASCOTA_OTRAS     CHECK (COMPATIBLE_OTRAS_MASCOTAS IN ('S','N')),
  CONSTRAINT CK_MASCOTA_NECESID   CHECK (TIENE_NECESIDADES_ESPECIALES IN ('S','N')),
  CONSTRAINT CK_MASCOTA_ACTIVO    CHECK (ACTIVO IN ('S','N')),
  CONSTRAINT CK_MASCOTA_SALIDA    CHECK (FECHA_SALIDA IS NULL OR FECHA_SALIDA >= FECHA_INGRESO),
  CONSTRAINT CK_MASCOTA_INACTIVA  CHECK (ACTIVO = 'S' OR OBSERVACIONES_ESTADO IS NOT NULL)
);

CREATE TABLE FOTOS_MASCOTAS (
  ID_FOTO       NUMBER GENERATED AS IDENTITY,
  ID_MASCOTA    NUMBER         NOT NULL,
  RUTA_ARCHIVO  VARCHAR2(255)  NOT NULL,
  ES_PRINCIPAL  CHAR(1)        DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_FOTOS_MASCOTAS PRIMARY KEY (ID_FOTO),
  CONSTRAINT CK_FOTO_PRINCIPAL CHECK (ES_PRINCIPAL IN ('S','N'))
);


-- =====================================================================
-- 4. ADOPCIÓN Y SEGUIMIENTO
-- =====================================================================

CREATE TABLE SOLICITUDES_ADOPCION (
  ID_SOLICITUD                              NUMBER GENERATED AS IDENTITY,
  DOCUMENTO                                 VARCHAR2(20)   NOT NULL,
  -- Cuestionario de compatibilidad: se diligencia al crear la fila
  ID_TIPO_VIVIENDA                          NUMBER         NOT NULL,
  TIPO_VIVIENDA_OTRO                        VARCHAR2(100),
  TIENE_ESPACIO_EXTERIOR                    CHAR(1)        NOT NULL,
  ID_TIEMPO_DISPONIBLE                      NUMBER         NOT NULL,
  TIEMPO_DISPONIBLE_OTRO                    VARCHAR2(100),
  EXPERIENCIA_PREVIA                        CHAR(1)        NOT NULL,
  EXPERIENCIA_PREVIA_OBSERVACIONES          VARCHAR2(300),
  DISPUESTO_NECESIDADES_ESPECIALES          CHAR(1)        NOT NULL,
  TIENE_NINOS_HOGAR                         CHAR(1)        NOT NULL,
  TIENE_OTRAS_MASCOTAS_HOGAR                CHAR(1)        NOT NULL,
  TIENE_OTRAS_MASCOTAS_HOGAR_OBSERVACIONES  VARCHAR2(300),
  FECHA_ENVIO                               DATE           DEFAULT SYSDATE NOT NULL,
  -- Proceso formal: lo diligencia el staff si la solicitud avanza
  ID_MASCOTA                                NUMBER,
  DOCUMENTO_STAFF_INICIO                    VARCHAR2(20),
  FECHA_INICIO                              DATE,
  FECHA_VENCIMIENTO                         DATE,
  FECHA_ENTREGA                             DATE,
  ID_ESTADO_PROCESO                         NUMBER         DEFAULT 1 NOT NULL,
  DOCUMENTO_STAFF_CIERRE                    VARCHAR2(20),
  FECHA_RESOLUCION                          DATE,
  OBSERVACIONES                             VARCHAR2(500),
  CONSTRAINT PK_SOLICITUDES_ADOPCION PRIMARY KEY (ID_SOLICITUD),
  CONSTRAINT CK_SOL_EXTERIOR     CHECK (TIENE_ESPACIO_EXTERIOR           IN ('S','N')),
  CONSTRAINT CK_SOL_EXPERIENCIA  CHECK (EXPERIENCIA_PREVIA               IN ('S','N')),
  CONSTRAINT CK_SOL_DISPUESTO    CHECK (DISPUESTO_NECESIDADES_ESPECIALES IN ('S','N')),
  CONSTRAINT CK_SOL_NINOS        CHECK (TIENE_NINOS_HOGAR                IN ('S','N')),
  CONSTRAINT CK_SOL_MASCOTAS     CHECK (TIENE_OTRAS_MASCOTAS_HOGAR       IN ('S','N')),
  CONSTRAINT CK_SOL_VENCE        CHECK (FECHA_VENCIMIENTO IS NULL OR FECHA_VENCIMIENTO > FECHA_INICIO),
  CONSTRAINT CK_SOL_ENTREGA      CHECK (FECHA_ENTREGA IS NULL OR FECHA_ENTREGA >= FECHA_INICIO),
  CONSTRAINT CK_SOL_STAFF_INI    CHECK (DOCUMENTO_STAFF_INICIO IS NULL OR DOCUMENTO_STAFF_INICIO <> DOCUMENTO),
  CONSTRAINT CK_SOL_STAFF_CIE    CHECK (DOCUMENTO_STAFF_CIERRE IS NULL OR DOCUMENTO_STAFF_CIERRE <> DOCUMENTO),
  -- En estado SOLICITUD (1) aun no hay tramite formal; desde ACTIVO (2) si
  CONSTRAINT CK_SOL_FORMALIZADA  CHECK (ID_ESTADO_PROCESO = 1
                                    OR (ID_MASCOTA             IS NOT NULL
                                        AND DOCUMENTO_STAFF_INICIO IS NOT NULL
                                        AND FECHA_INICIO       IS NOT NULL
                                        AND FECHA_VENCIMIENTO  IS NOT NULL))
);

CREATE TABLE SEGUIMIENTOS (
  ID_SEGUIMIENTO     NUMBER GENERATED AS IDENTITY,
  ID_SOLICITUD       NUMBER         NOT NULL,
  ID_ETAPA           NUMBER         NOT NULL,
  FECHA_PROGRAMADA   DATE           NOT NULL,
  FECHA_RESPUESTA    DATE,
  SOLICITA_CONTACTO  CHAR(1),
  COMENTARIO         VARCHAR2(500),
  PUNTAJE            NUMBER(3,2),
  ID_SEMAFORO        NUMBER,
  CONSTRAINT PK_SEGUIMIENTOS       PRIMARY KEY (ID_SEGUIMIENTO),
  CONSTRAINT UQ_SEGUIMIENTO_ETAPA  UNIQUE (ID_SOLICITUD, ID_ETAPA),
  CONSTRAINT CK_SEGUIM_CONTACTO    CHECK (SOLICITA_CONTACTO IN ('S','N')),
  CONSTRAINT CK_SEGUIM_RESPONDIDO  CHECK (FECHA_RESPUESTA IS NULL
                                     OR (SOLICITA_CONTACTO IS NOT NULL
                                         AND PUNTAJE       IS NOT NULL
                                         AND ID_SEMAFORO   IS NOT NULL))
);

CREATE TABLE RESPUESTAS_SEGUIMIENTO (
  ID_SEGUIMIENTO  NUMBER  NOT NULL,
  ID_PREGUNTA     NUMBER  NOT NULL,
  ID_OPCION       NUMBER  NOT NULL,
  CONSTRAINT PK_RESPUESTAS_SEGUIMIENTO PRIMARY KEY (ID_SEGUIMIENTO, ID_PREGUNTA)
);

CREATE TABLE NOTIFICACIONES (
  ID_NOTIFICACION       NUMBER GENERATED AS IDENTITY,
  DOCUMENTO             VARCHAR2(20),
  ID_TIPO_NOTIFICACION  NUMBER         NOT NULL,
  MENSAJE               VARCHAR2(255)  NOT NULL,
  ID_SOLICITUD          NUMBER         NOT NULL,
  FECHA_CREACION        DATE           DEFAULT SYSDATE NOT NULL,
  FECHA_LECTURA         DATE,
  CONSTRAINT PK_NOTIFICACIONES PRIMARY KEY (ID_NOTIFICACION),
  CONSTRAINT CK_NOTIF_LECTURA  CHECK (FECHA_LECTURA IS NULL OR FECHA_LECTURA >= FECHA_CREACION)
);


-- =====================================================================
-- 5. LLAVES FORÁNEAS
-- Ninguna lleva ON DELETE CASCADE: en ADOPET no se borra, se desactiva.
-- =====================================================================

-- Acceso y menú
ALTER TABLE PERFILES ADD CONSTRAINT FK_PERFILES_ROL
  FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL);

ALTER TABLE PERFILES_OPCIONES ADD CONSTRAINT FK_PEROPC_PERFIL
  FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL);

ALTER TABLE PERFILES_OPCIONES ADD CONSTRAINT FK_PEROPC_OPCION
  FOREIGN KEY (ID_OPCION_MENU) REFERENCES OPCIONES_MENU (ID_OPCION_MENU);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_PERFIL
  FOREIGN KEY (ID_PERFIL) REFERENCES PERFILES (ID_PERFIL);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_TIPO_DOC
  FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPOS_DOCUMENTO (ID_TIPO_DOCUMENTO);

ALTER TABLE USUARIOS ADD CONSTRAINT FK_USUARIOS_CIUDAD
  FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES (ID_CIUDAD);

-- Mascotas
ALTER TABLE RAZAS ADD CONSTRAINT FK_RAZAS_ESPECIE
  FOREIGN KEY (ID_ESPECIE) REFERENCES ESPECIES (ID_ESPECIE);

-- La especie no se guarda en MASCOTAS: se obtiene por JOIN a RAZAS.
ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_RAZA
  FOREIGN KEY (ID_RAZA) REFERENCES RAZAS (ID_RAZA);

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_TAMANIO
  FOREIGN KEY (ID_TAMANIO) REFERENCES TAMANIOS (ID_TAMANIO);

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_SEXO
  FOREIGN KEY (ID_SEXO) REFERENCES SEXOS (ID_SEXO);

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_ENERGIA
  FOREIGN KEY (ID_NIVEL_ENERGIA) REFERENCES NIVELES_ENERGIA (ID_NIVEL_ENERGIA);

ALTER TABLE MASCOTAS ADD CONSTRAINT FK_MASCOTAS_ESTADO
  FOREIGN KEY (ID_ESTADO_MASCOTA) REFERENCES ESTADOS_MASCOTA (ID_ESTADO_MASCOTA);

ALTER TABLE FOTOS_MASCOTAS ADD CONSTRAINT FK_FOTOS_MASCOTA
  FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS (ID_MASCOTA);

-- Solicitud de adopción
ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_USUARIO
  FOREIGN KEY (DOCUMENTO) REFERENCES USUARIOS (DOCUMENTO);

ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_TIPO_VIVIENDA
  FOREIGN KEY (ID_TIPO_VIVIENDA) REFERENCES TIPOS_VIVIENDA (ID_TIPO_VIVIENDA);

ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_TIEMPO
  FOREIGN KEY (ID_TIEMPO_DISPONIBLE) REFERENCES TIEMPOS_DISPONIBLES (ID_TIEMPO_DISPONIBLE);

ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_MASCOTA
  FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTAS (ID_MASCOTA);

ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_STAFF_INICIO
  FOREIGN KEY (DOCUMENTO_STAFF_INICIO) REFERENCES USUARIOS (DOCUMENTO);

ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_STAFF_CIERRE
  FOREIGN KEY (DOCUMENTO_STAFF_CIERRE) REFERENCES USUARIOS (DOCUMENTO);

ALTER TABLE SOLICITUDES_ADOPCION ADD CONSTRAINT FK_SOL_ESTADO
  FOREIGN KEY (ID_ESTADO_PROCESO) REFERENCES ESTADOS_PROCESO (ID_ESTADO_PROCESO);

-- Seguimiento
ALTER TABLE SEGUIMIENTOS ADD CONSTRAINT FK_SEGUIM_SOLICITUD
  FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES_ADOPCION (ID_SOLICITUD);

ALTER TABLE SEGUIMIENTOS ADD CONSTRAINT FK_SEGUIM_ETAPA
  FOREIGN KEY (ID_ETAPA) REFERENCES ETAPAS_SEGUIMIENTO (ID_ETAPA);

ALTER TABLE SEGUIMIENTOS ADD CONSTRAINT FK_SEGUIM_SEMAFORO
  FOREIGN KEY (ID_SEMAFORO) REFERENCES SEMAFOROS (ID_SEMAFORO);

-- Formulario del checkpoint
ALTER TABLE OPCIONES_CHECKPOINT ADD CONSTRAINT FK_OPCHK_PREGUNTA
  FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTAS_CHECKPOINT (ID_PREGUNTA);

ALTER TABLE RESPUESTAS_SEGUIMIENTO ADD CONSTRAINT FK_RESPSEG_SEGUIMIENTO
  FOREIGN KEY (ID_SEGUIMIENTO) REFERENCES SEGUIMIENTOS (ID_SEGUIMIENTO);

ALTER TABLE RESPUESTAS_SEGUIMIENTO ADD CONSTRAINT FK_RESPSEG_PREGUNTA
  FOREIGN KEY (ID_PREGUNTA) REFERENCES PREGUNTAS_CHECKPOINT (ID_PREGUNTA);

-- FK compuesta: la opción elegida debe pertenecer a la pregunta respondida
ALTER TABLE RESPUESTAS_SEGUIMIENTO ADD CONSTRAINT FK_RESPSEG_OPCION
  FOREIGN KEY (ID_OPCION, ID_PREGUNTA)
  REFERENCES OPCIONES_CHECKPOINT (ID_OPCION, ID_PREGUNTA);

-- Notificaciones
ALTER TABLE NOTIFICACIONES ADD CONSTRAINT FK_NOTIF_TIPO
  FOREIGN KEY (ID_TIPO_NOTIFICACION) REFERENCES TIPOS_NOTIFICACION (ID_TIPO_NOTIFICACION);

ALTER TABLE NOTIFICACIONES ADD CONSTRAINT FK_NOTIF_USUARIO
  FOREIGN KEY (DOCUMENTO) REFERENCES USUARIOS (DOCUMENTO);

ALTER TABLE NOTIFICACIONES ADD CONSTRAINT FK_NOTIF_SOLICITUD
  FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES_ADOPCION (ID_SOLICITUD);


-- =====================================================================
-- 6. ÍNDICES
-- =====================================================================

-- Correo único sin distinguir mayúsculas de minúsculas.
CREATE UNIQUE INDEX UX_USUARIOS_CORREO_LOWER
  ON USUARIOS (LOWER(CORREO));

-- Una sola foto principal por mascota.
-- Oracle ignora los NULL en índices únicos, así que la restricción
-- solo aplica a las filas marcadas como principales.
CREATE UNIQUE INDEX UX_FOTO_PRINCIPAL_POR_MASCOTA
  ON FOTOS_MASCOTAS (CASE WHEN ES_PRINCIPAL = 'S' THEN ID_MASCOTA END);

-- Un adoptante no puede tener dos trámites vigentes al tiempo.
-- Vigente = ACTIVO (2) o EN_PRUEBA (3). SOLICITUD (1) no cuenta:
-- una persona puede tener varias solicitudes sin formalizar.
CREATE UNIQUE INDEX UX_PROCESO_VIGENTE_POR_USUARIO
  ON SOLICITUDES_ADOPCION (CASE WHEN ID_ESTADO_PROCESO IN (2,3) THEN DOCUMENTO END);

-- Una mascota no puede estar comprometida en dos trámites vigentes.
CREATE UNIQUE INDEX UX_PROCESO_VIGENTE_POR_MASCOTA
  ON SOLICITUDES_ADOPCION (CASE WHEN ID_ESTADO_PROCESO IN (2,3) THEN ID_MASCOTA END);
