CREATE TABLE ROLES (
    ID_ROL      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_ROL  VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL),
    CONSTRAINT UQ_ROLES_NOMBRE UNIQUE (NOMBRE_ROL)
);

CREATE TABLE PERFILES (
    ID_PERFIL      NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ROL         NUMBER NOT NULL,
    NOMBRE_PERFIL  VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PERFILES PRIMARY KEY (ID_PERFIL),
    CONSTRAINT FK_PERFILES_ROLES FOREIGN KEY (ID_ROL)
        REFERENCES ROLES (ID_ROL)
);

CREATE TABLE OPCIONES (
    ID_OPCION      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_OPCION  VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_OPCIONES PRIMARY KEY (ID_OPCION),
    CONSTRAINT UQ_OPCIONES_NOMBRE UNIQUE (NOMBRE_OPCION)
);

CREATE TABLE PERMISOS (
    ID_PERMISO  NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_OPCION   NUMBER NOT NULL,
    ACCION      VARCHAR2(15) NOT NULL,
    CONSTRAINT PK_PERMISOS PRIMARY KEY (ID_PERMISO),
    CONSTRAINT FK_PERMISOS_OPCIONES FOREIGN KEY (ID_OPCION)
        REFERENCES OPCIONES (ID_OPCION),
    CONSTRAINT CK_PERMISOS_ACCION CHECK
        (ACCION IN ('CREAR', 'CONSULTAR', 'ACTUALIZAR', 'ELIMINAR')),
    CONSTRAINT UQ_PERMISOS_OPCION_ACCION UNIQUE (ID_OPCION, ACCION)
);

CREATE TABLE PERFILES_PERMISOS (
    ID_PERFIL   NUMBER NOT NULL,
    ID_PERMISO  NUMBER NOT NULL,
    CONSTRAINT PK_PERFILES_PERMISOS PRIMARY KEY (ID_PERFIL, ID_PERMISO),
    CONSTRAINT FK_PERPER_PERFILES FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFILES (ID_PERFIL) ON DELETE CASCADE,
    CONSTRAINT FK_PERPER_PERMISOS FOREIGN KEY (ID_PERMISO)
        REFERENCES PERMISOS (ID_PERMISO) ON DELETE CASCADE
);

CREATE TABLE USUARIOS (
    ID_USUARIO       NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_PERFIL        NUMBER NOT NULL,
    NOMBRE           VARCHAR2(100) NOT NULL,
    CORREO           VARCHAR2(150) NOT NULL,
    CONTRASENA_HASH  VARCHAR2(255) NOT NULL,
    ACTIVO           CHAR(1) DEFAULT 'S' NOT NULL,
    FECHA_REGISTRO   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIOS_PERFILES FOREIGN KEY (ID_PERFIL)
        REFERENCES PERFILES (ID_PERFIL),
    CONSTRAINT CK_USUARIOS_ACTIVO CHECK (ACTIVO IN ('S', 'N'))
);

CREATE UNIQUE INDEX UX_USUARIOS_CORREO_LOWER ON USUARIOS (LOWER(CORREO));
