CREATE TABLE ADOPTANTES (
    ID_USUARIO        NUMBER NOT NULL,
    DOCUMENTO         VARCHAR2(20) NOT NULL,
    TIPO_DOCUMENTO    VARCHAR2(15) NOT NULL,
    TELEFONO          VARCHAR2(20) NOT NULL,
    DIRECCION         VARCHAR2(200) NOT NULL,
    CIUDAD            VARCHAR2(80) NOT NULL,
    FECHA_NACIMIENTO  DATE NOT NULL,
    CONSTRAINT PK_ADOPTANTES PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_ADOPTANTES_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID_USUARIO),
    CONSTRAINT CK_ADOPTANTES_TIPO_DOC CHECK
        (TIPO_DOCUMENTO IN ('CC', 'CE', 'TI', 'PASAPORTE'))
);

CREATE UNIQUE INDEX UX_ADOPTANTES_DOCUMENTO_NORM
    ON ADOPTANTES (TIPO_DOCUMENTO, REPLACE(REPLACE(DOCUMENTO, '.', ''), ' ', ''));

CREATE TABLE CUESTIONARIOS (
    ID_CUESTIONARIO                   NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO                        NUMBER NOT NULL,
    TIPO_VIVIENDA                     VARCHAR2(15) NOT NULL,
    TIENE_ESPACIO_EXTERIOR            CHAR(1) NOT NULL,
    TIEMPO_DISPONIBLE                 VARCHAR2(10) NOT NULL,
    EXPERIENCIA_PREVIA                VARCHAR2(10) NOT NULL,
    DISPUESTO_NECESIDADES_ESPECIALES  CHAR(1) NOT NULL,
    TIENE_NINOS_HOGAR                 CHAR(1) NOT NULL,
    TIENE_OTRAS_MASCOTAS_HOGAR        CHAR(1) NOT NULL,
    FECHA_RESPUESTA                   DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CUESTIONARIOS PRIMARY KEY (ID_CUESTIONARIO),
    CONSTRAINT FK_CUESTIONARIOS_ADOPTANTES FOREIGN KEY (ID_USUARIO)
        REFERENCES ADOPTANTES (ID_USUARIO),
    CONSTRAINT UQ_CUESTIONARIOS_USUARIO UNIQUE (ID_CUESTIONARIO, ID_USUARIO),
    CONSTRAINT CK_CUESTIONARIOS_VIVIENDA CHECK
        (TIPO_VIVIENDA IN ('CASA', 'APARTAMENTO')),
    CONSTRAINT CK_CUESTIONARIOS_ESPACIO CHECK
        (TIENE_ESPACIO_EXTERIOR IN ('S', 'N')),
    CONSTRAINT CK_CUESTIONARIOS_TIEMPO CHECK
        (TIEMPO_DISPONIBLE IN ('POCO', 'MODERADO', 'MUCHO')),
    CONSTRAINT CK_CUESTIONARIOS_EXPERIENCIA CHECK
        (EXPERIENCIA_PREVIA IN ('NINGUNA', 'BASICA', 'AMPLIA')),
    CONSTRAINT CK_CUESTIONARIOS_DISPUESTO CHECK
        (DISPUESTO_NECESIDADES_ESPECIALES IN ('S', 'N')),
    CONSTRAINT CK_CUESTIONARIOS_NINOS CHECK
        (TIENE_NINOS_HOGAR IN ('S', 'N')),
    CONSTRAINT CK_CUESTIONARIOS_MASCOTAS CHECK
        (TIENE_OTRAS_MASCOTAS_HOGAR IN ('S', 'N'))
);
