CREATE TABLE MASCOTAS (
    ID_MASCOTA                    NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE                        VARCHAR2(50) NOT NULL,
    ESPECIE                       VARCHAR2(10) NOT NULL,
    RAZA                          VARCHAR2(50) NOT NULL,
    EDAD_MESES_INGRESO            NUMBER(3) NOT NULL,
    TAMANIO                       VARCHAR2(10) NOT NULL,
    SEXO                          VARCHAR2(10) NOT NULL,
    NIVEL_ENERGIA                 VARCHAR2(10) NOT NULL,
    COMPATIBLE_NINOS              CHAR(1) NOT NULL,
    COMPATIBLE_OTRAS_MASCOTAS     CHAR(1) NOT NULL,
    TIENE_NECESIDADES_ESPECIALES  CHAR(1) NOT NULL,
    DESCRIPCION_NECESIDADES       VARCHAR2(500),
    FECHA_INGRESO                 DATE DEFAULT SYSDATE NOT NULL,
    ESTADO                        VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL,
    MOTIVO_INACTIVA               VARCHAR2(200),
    CONSTRAINT PK_MASCOTAS PRIMARY KEY (ID_MASCOTA),
    CONSTRAINT CK_MASCOTAS_ESPECIE CHECK
        (ESPECIE IN ('PERRO', 'GATO')),
    CONSTRAINT CK_MASCOTAS_TAMANIO CHECK
        (TAMANIO IN ('PEQUENO', 'MEDIANO', 'GRANDE')),
    CONSTRAINT CK_MASCOTAS_SEXO CHECK
        (SEXO IN ('MACHO', 'HEMBRA')),
    CONSTRAINT CK_MASCOTAS_ENERGIA CHECK
        (NIVEL_ENERGIA IN ('BAJO', 'MEDIO', 'ALTO')),
    CONSTRAINT CK_MASCOTAS_COMP_NINOS CHECK
        (COMPATIBLE_NINOS IN ('S', 'N')),
    CONSTRAINT CK_MASCOTAS_COMP_MASCOTAS CHECK
        (COMPATIBLE_OTRAS_MASCOTAS IN ('S', 'N')),
    CONSTRAINT CK_MASCOTAS_NECESIDADES CHECK
        (TIENE_NECESIDADES_ESPECIALES IN ('S', 'N')),
    CONSTRAINT CK_MASCOTAS_ESTADO CHECK
        (ESTADO IN ('DISPONIBLE', 'EN_PROCESO', 'EN_PRUEBA', 'ADOPTADA', 'INACTIVA')),
    CONSTRAINT CK_MASCOTAS_EDAD CHECK
        (EDAD_MESES_INGRESO > 0),
    CONSTRAINT CK_MASCOTAS_MOTIVO_INACTIVA CHECK
        (ESTADO <> 'INACTIVA' OR MOTIVO_INACTIVA IS NOT NULL)
);

CREATE TABLE FOTOS_MASCOTAS (
    ID_FOTO       NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MASCOTA    NUMBER NOT NULL,
    RUTA_ARCHIVO  VARCHAR2(255) NOT NULL,
    ES_PRINCIPAL  CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT PK_FOTOS_MASCOTAS PRIMARY KEY (ID_FOTO),
    CONSTRAINT FK_FOTOS_MASCOTAS FOREIGN KEY (ID_MASCOTA)
        REFERENCES MASCOTAS (ID_MASCOTA) ON DELETE CASCADE,
    CONSTRAINT CK_FOTOS_PRINCIPAL CHECK (ES_PRINCIPAL IN ('S', 'N'))
);

CREATE UNIQUE INDEX UX_FOTO_PRINCIPAL_POR_MASCOTA
    ON FOTOS_MASCOTAS (CASE WHEN ES_PRINCIPAL = 'S' THEN ID_MASCOTA END);
