CREATE TABLE PROCESOS_ADOPCION (
    ID_PROCESO         NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_MASCOTA         NUMBER NOT NULL,
    ID_USUARIO         NUMBER NOT NULL,
    ID_CUESTIONARIO    NUMBER NOT NULL,
    ID_STAFF_INICIO    NUMBER NOT NULL,
    FECHA_INICIO       DATE DEFAULT SYSDATE NOT NULL,
    FECHA_VENCIMIENTO  DATE NOT NULL,
    FECHA_ENTREGA      DATE,
    ESTADO             VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    ID_STAFF_CIERRE    NUMBER,
    FECHA_RESOLUCION   DATE,
    OBSERVACIONES      VARCHAR2(500),
    CONSTRAINT PK_PROCESOS_ADOPCION PRIMARY KEY (ID_PROCESO),
    CONSTRAINT FK_PROCESOS_MASCOTAS FOREIGN KEY (ID_MASCOTA)
        REFERENCES MASCOTAS (ID_MASCOTA),
    CONSTRAINT FK_PROCESOS_ADOPTANTES FOREIGN KEY (ID_USUARIO)
        REFERENCES ADOPTANTES (ID_USUARIO),
    CONSTRAINT FK_PROCESOS_CUESTIONARIOS FOREIGN KEY (ID_CUESTIONARIO, ID_USUARIO)
        REFERENCES CUESTIONARIOS (ID_CUESTIONARIO, ID_USUARIO),
    CONSTRAINT FK_PROCESOS_STAFF_INICIO FOREIGN KEY (ID_STAFF_INICIO)
        REFERENCES USUARIOS (ID_USUARIO),
    CONSTRAINT FK_PROCESOS_STAFF_CIERRE FOREIGN KEY (ID_STAFF_CIERRE)
        REFERENCES USUARIOS (ID_USUARIO),
    CONSTRAINT CK_PROCESOS_ESTADO CHECK
        (ESTADO IN ('ACTIVO', 'EN_PRUEBA', 'FINALIZADO', 'FALLIDO', 'VENCIDO',
                    'CANCELADO_ADOPTANTE', 'CANCELADO_STAFF', 'CANCELADO_OTROS')),
    CONSTRAINT CK_PROCESOS_OBSERVACIONES CHECK
        (ESTADO <> 'CANCELADO_OTROS' OR OBSERVACIONES IS NOT NULL),
    CONSTRAINT CK_PROCESOS_ENTREGA CHECK
        (ESTADO NOT IN ('EN_PRUEBA', 'FINALIZADO', 'FALLIDO')
         OR FECHA_ENTREGA IS NOT NULL),
    CONSTRAINT CK_PROCESOS_RESOLUCION CHECK
        (ESTADO IN ('ACTIVO', 'EN_PRUEBA') OR FECHA_RESOLUCION IS NOT NULL),
    CONSTRAINT CK_PROCESOS_STAFF_CIERRE CHECK
        (ESTADO <> 'FINALIZADO' OR ID_STAFF_CIERRE IS NOT NULL),
    CONSTRAINT CK_PROCESOS_FECHA_VENC CHECK
        (FECHA_VENCIMIENTO > FECHA_INICIO),
    CONSTRAINT CK_PROCESOS_FECHA_ENTREGA CHECK
        (FECHA_ENTREGA IS NULL OR FECHA_ENTREGA >= FECHA_INICIO)
);

CREATE UNIQUE INDEX UX_PROCESO_VIGENTE_POR_USUARIO
    ON PROCESOS_ADOPCION (CASE WHEN ESTADO IN ('ACTIVO', 'EN_PRUEBA') THEN ID_USUARIO END);

CREATE UNIQUE INDEX UX_PROCESO_VIGENTE_POR_MASCOTA
    ON PROCESOS_ADOPCION (CASE WHEN ESTADO IN ('ACTIVO', 'EN_PRUEBA') THEN ID_MASCOTA END);

CREATE TABLE SEGUIMIENTOS (
    ID_SEGUIMIENTO     NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_PROCESO         NUMBER NOT NULL,
    ETAPA              VARCHAR2(10) NOT NULL,
    FECHA_PROGRAMADA   DATE NOT NULL,
    FECHA_RESPUESTA    DATE,
    ADAPTACION         VARCHAR2(10),
    ALIMENTACION       VARCHAR2(10),
    SALUD              VARCHAR2(20),
    COMPORTAMIENTO     VARCHAR2(20),
    CONVIVENCIA        VARCHAR2(10),
    ESTADO_ADOPTANTE   VARCHAR2(20),
    SOLICITA_CONTACTO  CHAR(1),
    TIEMPO_DEDICADO    VARCHAR2(20),
    NOCHES             VARCHAR2(10),
    COMENTARIO         VARCHAR2(500),
    SEMAFORO           VARCHAR2(10),
    CONSTRAINT PK_SEGUIMIENTOS PRIMARY KEY (ID_SEGUIMIENTO),
    CONSTRAINT FK_SEGUIMIENTOS_PROCESOS FOREIGN KEY (ID_PROCESO)
        REFERENCES PROCESOS_ADOPCION (ID_PROCESO),
    CONSTRAINT UQ_SEGUIMIENTOS_ETAPA UNIQUE (ID_PROCESO, ETAPA),
    CONSTRAINT UQ_SEGUIMIENTOS_PROCESO UNIQUE (ID_SEGUIMIENTO, ID_PROCESO),
    CONSTRAINT CK_SEGUIMIENTOS_ETAPA CHECK
        (ETAPA IN ('DIA_3', 'SEMANA_3', 'MES_3')),
    CONSTRAINT CK_SEGUIMIENTOS_ADAPTACION CHECK
        (ADAPTACION IN ('BUENA', 'REGULAR', 'MALA')),
    CONSTRAINT CK_SEGUIMIENTOS_ALIMENTACION CHECK
        (ALIMENTACION IN ('NORMAL', 'IRREGULAR', 'NO_COME')),
    CONSTRAINT CK_SEGUIMIENTOS_SALUD CHECK
        (SALUD IN ('SIN_NOVEDAD', 'EN_OBSERVACION', 'REQUIERE_ATENCION')),
    CONSTRAINT CK_SEGUIMIENTOS_COMPORTAMIENTO CHECK
        (COMPORTAMIENTO IN ('SIN_PROBLEMAS', 'PROBLEMAS_LEVES', 'PROBLEMAS_GRAVES')),
    CONSTRAINT CK_SEGUIMIENTOS_CONVIVENCIA CHECK
        (CONVIVENCIA IN ('BUENA', 'REGULAR', 'MALA')),
    CONSTRAINT CK_SEGUIMIENTOS_ADOPTANTE CHECK
        (ESTADO_ADOPTANTE IN ('FELIZ', 'BIEN', 'ABRUMADO', 'EVALUANDO_ENTREGA')),
    CONSTRAINT CK_SEGUIMIENTOS_CONTACTO CHECK
        (SOLICITA_CONTACTO IN ('S', 'N')),
    CONSTRAINT CK_SEGUIMIENTOS_TIEMPO CHECK
        (TIEMPO_DEDICADO IN ('COMO_ESPERABA', 'MENOS_DEL_PENSADO', 'MUY_POCO')),
    CONSTRAINT CK_SEGUIMIENTOS_NOCHES CHECK
        (NOCHES IN ('TRANQUILAS', 'MOVIDAS', 'DIFICILES')),
    CONSTRAINT CK_SEGUIMIENTOS_SEMAFORO CHECK
        (SEMAFORO IN ('VERDE', 'AMARILLO', 'ROJO')),
    CONSTRAINT CK_SEGUIMIENTOS_COMPLETO CHECK
        (FECHA_RESPUESTA IS NULL
         OR (ADAPTACION IS NOT NULL
             AND ALIMENTACION IS NOT NULL
             AND SALUD IS NOT NULL
             AND COMPORTAMIENTO IS NOT NULL
             AND CONVIVENCIA IS NOT NULL
             AND ESTADO_ADOPTANTE IS NOT NULL
             AND SOLICITA_CONTACTO IS NOT NULL
             AND TIEMPO_DEDICADO IS NOT NULL
             AND NOCHES IS NOT NULL
             AND SEMAFORO IS NOT NULL))
);

CREATE TABLE NOTIFICACIONES (
    ID_NOTIFICACION     NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO          NUMBER,
    TIPO                VARCHAR2(30) NOT NULL,
    MENSAJE             VARCHAR2(255) NOT NULL,
    ID_PROCESO          NUMBER NOT NULL,
    ID_SEGUIMIENTO      NUMBER,
    FECHA_CREACION      DATE DEFAULT SYSDATE NOT NULL,
    FECHA_LECTURA       DATE,
    ID_USUARIO_LECTURA  NUMBER,
    CONSTRAINT PK_NOTIFICACIONES PRIMARY KEY (ID_NOTIFICACION),
    CONSTRAINT FK_NOTIF_USUARIOS FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS (ID_USUARIO),
    CONSTRAINT FK_NOTIF_USUARIO_LECTURA FOREIGN KEY (ID_USUARIO_LECTURA)
        REFERENCES USUARIOS (ID_USUARIO),
    CONSTRAINT FK_NOTIF_PROCESOS FOREIGN KEY (ID_PROCESO)
        REFERENCES PROCESOS_ADOPCION (ID_PROCESO),
    CONSTRAINT FK_NOTIF_SEGUIMIENTOS FOREIGN KEY (ID_SEGUIMIENTO, ID_PROCESO)
        REFERENCES SEGUIMIENTOS (ID_SEGUIMIENTO, ID_PROCESO),
    CONSTRAINT CK_NOTIF_TIPO CHECK
        (TIPO IN ('CHECKPOINT_PENDIENTE', 'CHECKPOINT_POR_VENCER',
                  'CHECKPOINT_SIN_RESPUESTA', 'SEMAFORO_ROJO', 'SOLICITA_CONTACTO',
                  'PROCESO_POR_VENCER', 'PROCESO_VENCIDO', 'PRUEBA_CUMPLIDA',
                  'PROCESO_CERRADO')),
    CONSTRAINT CK_NOTIF_LECTURA CHECK
        (ID_USUARIO_LECTURA IS NULL OR FECHA_LECTURA IS NOT NULL)
);
