INSERT INTO ROLES (NOMBRE_ROL) VALUES ('ADOPTANTE');
INSERT INTO ROLES (NOMBRE_ROL) VALUES ('STAFF');

INSERT INTO PERFILES (ID_ROL, NOMBRE_PERFIL)
SELECT ID_ROL, 'Adoptante' FROM ROLES WHERE NOMBRE_ROL = 'ADOPTANTE';

INSERT INTO PERFILES (ID_ROL, NOMBRE_PERFIL)
SELECT ID_ROL, 'Staff general' FROM ROLES WHERE NOMBRE_ROL = 'STAFF';

INSERT INTO OPCIONES (NOMBRE_OPCION) VALUES ('USUARIOS');
INSERT INTO OPCIONES (NOMBRE_OPCION) VALUES ('MASCOTAS');
INSERT INTO OPCIONES (NOMBRE_OPCION) VALUES ('CUESTIONARIOS');
INSERT INTO OPCIONES (NOMBRE_OPCION) VALUES ('PROCESOS_ADOPCION');
INSERT INTO OPCIONES (NOMBRE_OPCION) VALUES ('SEGUIMIENTOS');
INSERT INTO OPCIONES (NOMBRE_OPCION) VALUES ('NOTIFICACIONES');

INSERT INTO PERMISOS (ID_OPCION, ACCION)
SELECT o.ID_OPCION, a.ACCION
FROM OPCIONES o
CROSS JOIN (
    SELECT 'CREAR'      AS ACCION FROM DUAL UNION ALL
    SELECT 'CONSULTAR'  FROM DUAL UNION ALL
    SELECT 'ACTUALIZAR' FROM DUAL UNION ALL
    SELECT 'ELIMINAR'   FROM DUAL
) a;

INSERT INTO PERFILES_PERMISOS (ID_PERFIL, ID_PERMISO)
SELECT pf.ID_PERFIL, pm.ID_PERMISO
FROM PERFILES pf
CROSS JOIN PERMISOS pm
WHERE pf.NOMBRE_PERFIL = 'Staff general';

INSERT INTO PERFILES_PERMISOS (ID_PERFIL, ID_PERMISO)
SELECT pf.ID_PERFIL, pm.ID_PERMISO
FROM PERFILES pf
CROSS JOIN PERMISOS pm
JOIN OPCIONES o ON o.ID_OPCION = pm.ID_OPCION
WHERE pf.NOMBRE_PERFIL = 'Adoptante'
  AND (
        (o.NOMBRE_OPCION = 'USUARIOS'          AND pm.ACCION IN ('CONSULTAR', 'ACTUALIZAR'))
     OR (o.NOMBRE_OPCION = 'MASCOTAS'          AND pm.ACCION = 'CONSULTAR')
     OR (o.NOMBRE_OPCION = 'CUESTIONARIOS'     AND pm.ACCION IN ('CREAR', 'CONSULTAR'))
     OR (o.NOMBRE_OPCION = 'PROCESOS_ADOPCION' AND pm.ACCION = 'CONSULTAR')
     OR (o.NOMBRE_OPCION = 'SEGUIMIENTOS'      AND pm.ACCION IN ('CONSULTAR', 'ACTUALIZAR'))
     OR (o.NOMBRE_OPCION = 'NOTIFICACIONES'    AND pm.ACCION IN ('CONSULTAR', 'ACTUALIZAR'))
  );
